apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "common.fullname" . }}-init-scripts
  labels:
    {{- include "common.labels" . | nindent 4 }}
data:
  {{- with .Values.initdbScripts }}
    {{- toYaml . | nindent 2 }}
  {{- end }}