{{- if .Values.ingress.enabled -}}
apiVersion: traefik.io/v1alpha1
kind: IngressRouteTCP
metadata:
  name: {{ include "common.fullname" . }}
  labels:
    {{- include "common.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- toYaml .Values.ingress.entryPoints | nindent 4 }}
  routes:
    - match: HostSNI(`{{ include "common.hostname" . }}`)
      services:
        - name: {{ include "common.fullname" . }}
          port: 5432
  
  tls:
    secretName: {{ include "common.fullname" . }}-tls
    passthrough: false 
{{- end }}